// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: eackqbdskseslfjctmgk

class SupabaseConfig {
  static const String supabaseUrl = 'https://eackqbdskseslfjctmgk.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhY2txYmRza3Nlc2xmamN0bWdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAxNTYxMTQsImV4cCI6MjA4NTczMjExNH0.yfawrHkEGjhRKXQ3cOWSeUP_m_Qx8ceUQGI6Y9L0hJs';
}
